name: Check and verify files are available on S3

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  schedule:
    - cron: '0 9 * * 0'  # Every Sunday at 9 AM UTC
  workflow_dispatch:

jobs:
  verify_s3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup uv
        uses: astral-sh/setup-uv@v7
      - name: Install tools
        run: |
          uv tool install git-annex
          uv tool install datalad
      - name: git identification
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "nipreps@gmail.com"
      - name: Install all datasets
        run: uvx datalad install -r .
      - name: Check S3 files
        run: uv run .github/scripts/check-s3.py
        env:
          CONCURRENT_REQUESTS: 50
